### ISSUE TITLE
NoMethodError: private method `errors' called for action

### ISSUE THREAD

**Issue by jodosha** [hanami/controller#147]
Reported by @nickmorlan in chat.

The problem is caused by `session.rb`, that defines `errors` as a private method.

Here's a stack trace:
https://gist.github.com/nickmorlan/4ce60b1632f115152289

**Comment by huynhquancam** [comment]
@jodosha Could you brief the full context of the chat or the steps to reproduce the error?

**Comment by nickmorlan** [comment]
Hope this is helpful, I am a noob around here.
I followed the getting started guide(http://hanamirb.org/guides/getting-started/), setting up the book repository and tests.  After finishing the guide I set sessions in the generated application.rb file line 77
` sessions :cookie, secret: ENV['WEB_SESSIONS_SECRET'] `
When enabling sessions, the create_book.rb test would throw an error stating that errors was a private method.  Looks like the sessions file redefines or makes the errors private and the tests cannot access errors without explicitly looking at the param errors.

From the guide the create_book.rb line
`action.errors.for('book.title').wont_be_empty`
now throws an error when enabling sessions.  Changing it to 
`action.params.errors.for('book.title').wont_be_empty`
makes the test pass

**Comment by huynhquancam** [comment]
Got you @nickmorlan, then I guess making Hanami::Action::Session#errors method public will do?

**Comment by nickmorlan** [comment]
That would be my assumption, but I am not sure what the expected behavior is or if there is something that would interfere.

**Comment by vasspilka** [comment]
@huynhquancam If its a simple private to public conversion I can can take this on, if you don't mind.
