### ISSUE TITLE
call to Hanami::Action#call with params shouldn't modify (stringify) params

### ISSUE THREAD

**Issue by Incanus3** [hanami/controller#154]
Hi,
I've worked through your getting started guide at http://hanamirb.org/guides/getting-started/ and I love the architecture of the project (especially in contrast to rails). I ran into one issue though - the example spec in 'Implementing Create action' section doesn't work any more, since the `action.call(params)` call stringifies `params` as a side-effect, thus making the following `params[:book][:title]` expression in the `action.book.title.must_equal params[:book][:title]` assertion return `nil`. I've traced the call path through hanami/controller and hanami/utils and [this](https://github.com/hanami/utils/blob/0.8.x/lib/hanami/utils/attributes.rb#L33) is where it happens. What I think should be done is to deep-clone the hash either there or before [this call](https://github.com/hanami/controller/blob/0.7.x/lib/hanami/action/params.rb#L248). I'm using these versions of the gems:

gem 'hanami',             github: 'hanami/hanami',      branch: '0.8.x'
gem 'hanami-utils',       github: 'hanami/utils',       branch: '0.8.x'
gem 'hanami-router',      github: 'hanami/router',      branch: '0.7.x'
gem 'hanami-controller',  github: 'hanami/controller',  branch: '0.7.x'
gem 'hanami-view',        github: 'hanami/view',        branch: '0.7.x'
gem 'hanami-model',       github: 'hanami/model',       branch: '0.7.x'
gem 'hanami-validations', github: 'hanami/validations', branch: '0.6.x'
gem 'hanami-helpers',     github: 'hanami/helpers',     branch: '0.4.x'
gem 'hanami-mailer',      github: 'hanami/mailer',      branch: '0.3.x'
gem 'hanami-assets',      github: 'hanami/assets',      branch: '0.3.x'

I tried to reproduce in master, but I'm having problems with connecting to the database. Looking at the master code though, I think the problem will problem will remain. For now, I think at least the example test in documentation should be updated to assert on the actual title value.

**Comment by Erol** [comment]
I think this is related to https://github.com/hanami/controller/issues/70.

> With the next release we will remove indifferent access, by providing symbol only keys.

So this should be addressed in Hanami 0.8.0 👍

**Comment by Incanus3** [comment]
Thanks, that's good to hear, but I think there are actually two different issues here - one is the indifferent access when working with Hanami::Action::Params (or Hanami::Utils::Attributes), the other (and more surprising) is the side-effect of changing the plain Hash passed into Hanami::Action#call, which might happen even after removing indifferent access, if the hash is not deep-cloned before being symbolized.

**Comment by jodosha** [comment]
@Incanus3 Hi and thanks for reporting this issue.

In master there is a new way to handle params and shouldn't mutate them anymore. Can you please test with:

```ruby
# dry-* gems are temporary needed until they release stable versions
gem 'dry-types',                require: false, github: 'dry-rb/dry-types'
gem 'dry-logic',                require: false, github: 'dry-rb/dry-logic'
gem 'dry-validation',           require: false, github: 'dry-rb/dry-validation'

gem 'hanami-validations', github: 'hanami/validations', branch: 'master'
gem 'hanami-controller', github: 'hanami/controller', branch: 'master'
```

**Comment by Incanus3** [comment]
I'll try to get to it through the weekend

**Comment by Incanus3** [comment]
@jodosha I don't think this works yet (without modifying passed-in params hash). I did this simple test:

```
# Gemfile
source 'https://rubygems.org'

gem 'dry-types',                require: false, github: 'dry-rb/dry-types'
gem 'dry-logic',                require: false, github: 'dry-rb/dry-logic'
gem 'dry-validation',           require: false, github: 'dry-rb/dry-validation'

gem 'hanami-validations', github: 'hanami/validations', branch: 'master'
gem 'hanami-controller',  github: 'hanami/controller',  branch: 'master'
gem 'hanami-utils',       github: 'hanami/utils',       branch: 'master'
```

```
# test.rb
require 'hanami/controller'

class Action
  include Hanami::Action

  def call(params)
  end
end

params = { a: 1, b: { c: 2, d: 3 }}

p params
Action.new.call(params)
p params
```

This produces the following output:
```
{:a=>1, :b=>{:c=>2, :d=>3}}
{:a=>1, :b=>{"c"=>2, "d"=>3}}
```
So the keys of nested params are evidently stringified.

PS: just to be sure, I checked Gemfile.lock and it uses hanami-controller commit e6ed4f77cb06505879fc07ac126edc4d6fd80588, which is the latest as of now.

**Comment by jodosha** [comment]
@Incanus3 Hey, thanks for your reply.

You may still be using `hanami-controller` from the installed gem. The file `test.rb` lacks of `require 'bundler/setup'`. With that line here's my output:

```ruby
{:a=>1, :b=>{:c=>2, :d=>3}}
{:a=>1, :b=>{:c=>2, :d=>3}}
```

While without bundler, we get the same output.

---

To be double sure, please print `Hanami::Controller::VERSION`, it should be `0.7.0`, which will be the next version. If you see `0.6.1`, you're not using master.

---

Can you please verify? Thanks 😄

**Comment by Incanus3** [comment]
@jodosha You're completely right. If I don't `require 'bundler/setup'`, it uses 0.6.1 and if I do, it works as expected. Sorry about the false negative, should've run it through bundle exec. I've been working on a React side project this last two months, so I kind of fell out of the habit. When can we expect hanami-controller 0.7.0 to be released as part of hanami?

PS: thanks for the great work guys, I love what you're doing. If I have enough time in the future, I'd very much like to get involved (hopefully not on an already solved issue :laughing:)

**Comment by jodosha** [comment]
@Incanus3 
> When can we expect hanami-controller 0.7.0 to be released as part of hanami?

In a month, but you can depend on `0.7.x` branch. `hanami-controller` is the most stable component that we have. 😉
