### ISSUE TITLE
Built In Authentication

### ISSUE THREAD

**Issue by jasoncharnes** [hanami/controller#157]
This may not be the proper channel for this discussion. If not, please let me know and I'll make sure to post accordingly in the future.

I was curious if there was room for discussion, or had already been any discussion, about integrating an authentication system into Hanami. I've seen this in the PHP framework [Laravel](https://laravel.com/docs/5.2/authentication) and it is always something that has interested me. Providing a solution for authentication out of the box. This is a problem solved in Rails by using Devise. Devise is great, but yet another dependency.

I know that being lightweight is one of Hanami's strong points, so I'm not sure if this would be _too_ much, but I'd love to talk more about it. If not, no worries 😄

**Comment by jodosha** [comment]
@jasoncharnes Hey thanks for asking, but this is out of scope.

Hanami is Rack based, there are really good libraries out there to serve this purpose. See `warden` and `omniauth`.

IMO Devise is child of Rails philosophy which does too much for convenience sake. I hope that Hanami Community doesn't try to imitate this library with its mistakes.

---

You can post future conversations over here: https://discuss.hanamirb.org 🐈

**Comment by jasoncharnes** [comment]
That makes sense. Thank you for taking the time to reply!

**Comment by cllns** [comment]
@jasoncharnes If you're interested in trying out `rodauth`, check out: https://github.com/davydovanton/hanami-rodauth by @davydovanton :)
