### ISSUE TITLE
Exceptions raised from callbacks aren't handled by handle_exceptions

### ISSUE THREAD

**Issue by jodosha** [hanami/controller#159]
Example:

```ruby
module Projects
  class Show
    include Hanami::Action

    configuration.handle_exceptions true
    handle_exception ActiveRecord::RecordNotFound => 404

    before :find_account!

    def call(params)
      @account.projects.find(params[:id])
    end

    private

    def find_account!
      @account = Account.find(params[:account_id])
    end
  end
end
```

When this action is called, instead of handle the `ActiveRecord::RecordNotFound` exception as a `404`, it blows up. Probably this happens because callbacks are executed outside of the `_rescue` block, which is responsible of exceptions handling.

**Comment by vladimirich** [comment]
I'm really want to help, but I'm not sure I can handle it quickly. If it's not a critical bug and can wait for couple of weeks, I'd be glad to take this issue

**Comment by vladimirich** [comment]
btw, works for me with latest version of hanami-controller. When I tried to paste `handle_exceptions true` inside `class Show` it blows up with `undefined method `handle_exceptions'`. So I configured in hanamis application.rb and all works just fine.

**Comment by vladimirich** [comment]
btw, can't reproduce this bug. Works on latest hanami-contoller version just fine. Only one difference with your code is that I moved `handle_exceptions true` inside hanamis application.rb, because your version blows up with `undefined method `handle_exceptions'`.

**Comment by jodosha** [comment]
@vladimirich Hey thanks for your help. You can't reproduce, because there is a typo in the example above, which I now fixed.

**Comment by jodosha** [comment]
I think @vladimirich is right: this isn't a bug. This is an issue that I experienced in production. The code above is a simplified version of it. It could've been happened that the error was caused from something else (not related to callbacks).

Here's the complete code, which works as expected:

```ruby
require 'bundler/setup'
require 'hanami/controller'

class RecordNotFound < StandardError
end

class Account
  def self.find(id)
    raise RecordNotFound
  end
end

module Projects
  class Show
    include Hanami::Action

    configuration.handle_exceptions true
    handle_exception RecordNotFound => 404

    before :find_account!

    def call(params)
      @account.projects.find(params[:id])
    end

    private

    def find_account!
      @account = Account.find(params[:account_id])
    end
  end
end

response = Projects::Show.new.call(account_id: 1, id: 2)
puts response.inspect
# => [404, {"Content-Type"=>"application/octet-stream; charset=utf-8"}, ["Not Found"]]
```

I tested both with stable (`hanami-controller` `0.6.1`) and master (at 47341f1). They both work as expected.

---

I added a couple of specs to prove that this works as expected: https://github.com/hanami/controller/commit/2140038efea7bdcbb6083730540e59aad63d7838

---

Closing this and marking as invalid.
