### ISSUE TITLE
Routes and helpers - how to get them as objects

### ISSUE THREAD

**Issue by apotonick** [hanami/controller#161]
Hey, working on a nice example project with Hanami and Trailblazer. It's great fun. :heart:  I have two things, though, I'd love to discuss when using [Cells](http://trailblazer.to/gems/cells) with Hanami.

## Cells in Hanami

We use Cells as a replacement for `Hanami::View`, we simply render the cell in the `Action.

```ruby
class Create
  include Hanami::Action

  def call(params)
    # whatever
    self.body = Some::Cell.(bla, routes: routes).() # note the :routes injection.
  end
end
```

As you can see, the cell's returned markup is assigned via `Action#body=` and done. It works great so far.

## Route object

In the cell, you might want to use Hanami's route helpers. This I do by injecting `routes` from the controller into the cell (see above), then in the cell or its view I call something along `routes.sheets_path` and it works.

My first question now is: Can we access the `routes` object without having to have a controller? This is especially helpful in tests, where we *currently* need a controller to get a route object.

```ruby
it do
  controller = My::Controller.new
  
  html = Some::Cell.(bla, 
    routes: controller.routes).() # can we do without controller somehow here?
end
```

## Asset Helpers

The other problem is: how can we access the asset helpers such as `javascript_tag` without including a helper module into the cell? I would love to have a `helpers` object here, so the cell doesn't get polluted with Hanami helpers.

Currently, I have the following hack.

```ruby
class Create
  include Hanami::Action
  includer.send :include, Hanami::Assets::Helpers # this might not be how it's intended.

  def call(params)
    # whatever
    self.body = Some::Cell.(bla, routes: routes, helpers: self).() # note :helers injection.
  end
end
```

With this hack, in the cell, we can do `helpers.javascript_tag` and it works out nicely.

Again, in the test, this requires a controller.

## What we need

My goal is to have objects that provide helper methods as opposed to mixing them into the cell "The Rails Way™". Even if I `include` the `Assets::Helpers` into the cell, it complains about a missing `configuration`. 

This must be because of Hanami's global configuration system which I really do not wanna touch with Cells.

Any ideas how we could provide those two objects without a controller? :beers:

**Comment by jodosha** [comment]
@apotonick Hi Nick!

> My first question now is: Can we access the routes object without having to have a controller?

If you're using full stack Hanami, there are special constants like `Web::Routes` that respond to `.path`, `.url` and `.recognize`

---

One solution for helpers could be:

```ruby
class Helpers
  def self.configuration
    # Return an instance of Hanami::Assets::Configuration
  end

  include Hanami::Helpers
end
```

What do you think?

**Comment by apotonick** [comment]
That all makes sense, thanks! One question, though. How would I "Return an instance of Hanami::Assets::Configuration" ???

**Comment by jodosha** [comment]
@apotonick if you use the conventional namespace structure you can use `Configuration.for`.

```ruby
module Web
  class Helpers
    def self.configuration
      Hanami::Assets::Configuration.for(self)
    end

    include Hanami::Helpers
  end
end
```

This should work.

> Even if I include the Assets::Helpers into the cell, it complains about a missing configuration.

Can you please paste the stack trace here? So I can be sure that the suggested code above will work 😉 .
