### ISSUE TITLE
Array of schema in params: How to?

### ISSUE THREAD

**Issue by lasseebert** [hanami/controller#169]
I have an endpoint that accepts an array of hashes and I can't seem to make the validation work.

I have something like this in my action:

```ruby
params do
  optional(:my_items).filled do
    each do
      schema do
        requires(:foo).filled(:str?)
        requires(:bar).filled(:str?)
      end
    end
  end
end
```

I submit this: `my_items[0][foo]=a&my_items[0][bar]=b&my_items[1][foo]=c&my_items[1][bar]=d`

When the params reach my controller code, they are not valid since the above is interpretted as a hash:

```ruby
{
  "my_items" => {
    "0" => { "foo" => "a", "bar" => "b" },
    "1" => { "foo" => "c", "bar" => "d" }
  }
}
```

1, Am I doing something wrong?
2. Is it possible to preprocess the params so that I can modify it myself and e.g. change that hash to an array before it hits the validation part? Somewhere in between where params are parsed and where they are validated.

**Comment by cllns** [comment]
What about changing `optional(:my_items).filled do` to `required(:my_items).maybe do`? Would that work for you?

```
params do
  required(:my_items).maybe do
    each do
      schema do
        requires(:foo).filled(:str?)
        requires(:bar).filled(:str?)
      end
    end
  end
end
```

**Comment by lasseebert** [comment]
Thanks for the suggestion. It wouldn't work, because the parameter _is_ optional. As far as I understand `required(:my_items).maybe` means that the key `my_items` must be submitted, but it does not have to have a value.

**Comment by cllns** [comment]
Ah, ok.

It looks like your `  optional(:my_items).filled do` should be `  optional(:my_items).schema do` instead, since it's a nested validation. http://dry-rb.org/gems/dry-validation/nested-data/

**Comment by lasseebert** [comment]
I tried that, and it didn't do what I want either. `my_items` should be an array of schemas. So the output of the params after coercion should be something like:

```
{
  my_items: [
    { foo: "a", bar: "b" },
    { foo: "c", bar: "d" }
  ]
}
```

I have not been able to create a schema that supports that yet, so for now I'll use `optional(:basket).maybe` and then parse and validate the content of that myself.

**Comment by cllns** [comment]
@solnic any ideas?

**Comment by solnic** [comment]
It's not how rack params parsing works, you gotta do this:

```
my_items[][foo]=a&my_items[][bar]=b&my_items[][foo]=c&my_items[][bar]=....
``

**Comment by lasseebert** [comment]
Thanks for the clarification, @solnic.
Unfortunately, I don't control the input, so I will just write a middleware that changes it to the correct format.

**Comment by jodosha** [comment]
@solnic @cllns Thanks for replying!
