### ISSUE TITLE
Array of schemas

### ISSUE THREAD

**Issue by TiteiKo** [hanami/controller#175]
Hi all,

I can't seem to figure out how to make things work with an array of schemas as parameters... I've seen https://github.com/hanami/controller/issues/169 but it doesn't answer my problem...

See the following test:

```ruby
require 'spec_helper'

describe 'test params' do
  class TestParams < Web::Action::Params
    params do
      required(:foo).schema do
        required(:bar).filled do
          each do
            schema do
              required(:baz) { filled? & str? }
            end
          end
        end
      end
    end
  end

  it 'validates correctly' do
    p TestParams.new(foo: { bar: [{ baz: 'foobar' }] }).errors
    assert TestParams.new(foo: { bar: [{ baz: 'foobar' }] }).valid?
  end
end
```

Which outputs:

```
{:foo=>{:bar=>{0=>["must be a hash"]}}}

  1) Failure:
test params#test_0001_validates correctly [/theproject/spec/web/params/test_params_spec.rb:21]:
Expected false to be truthy.
````

I tried several variations in the schema, but so far, no luck in making this work...

**Comment by TiteiKo** [comment]
@theCrab These changes brakes the test:

```
gems/dry-types-0.8.1/lib/dry/types/compiler.rb:15:in `visit': undefined method `visit_b' for #<Dry::Types::Compiler:0x007ff97882c1b0 @registry=Dry::Types> (NoMethodError)
```

**Comment by TiteiKo** [comment]
Ok, so, I've now got the following:

```ruby
require 'spec_helper'

describe 'test params' do
  class TestParams < Web::Action::Params
    params do
      required(:foo).schema do
        required(:bar).each do
          schema do
            required(:baz) { filled? & str? }
          end
        end
      end
    end
  end

  it 'validates correctly' do
    p TestParams.new(foo: { bar: [{ baz: 'foobar' }] }).errors
    assert TestParams.new(foo: { bar: [{ baz: 'foobar' }] }).valid?
  end

  it 'validates correctly the corresponding dry validation schema' do
    schema = Dry::Validation.Schema do
      required(:foo).schema do
        required(:bar).each do
          schema do
            required(:baz) { filled? & str? }
          end
        end
      end
    end

    assert schema.call(foo: { bar: [{ baz: 'foobar' }] }).messages.empty?
  end
end
```

First test still does not pass:

```
{:foo=>{:bar=>{0=>["must be a hash"]}}}

  1) Failure:
test params#test_0001_validates correctly [/theproject/spec/web/params/test_params_spec.rb:18]:
Expected false to be truthy.
```

Second test passes.

From what I understand, dry-validation being used, the first test should pass too. Could ```{ baz: 'foobar' }``` have been stringified somewhere along the way?

**Comment by cllns** [comment]
@TiteiKo thanks! I think this might be related to @solnic's answer for #169. That is, it has to do with how Rack interprets parameters.

This article helps a bit, it refers to Rails but I think it's all from Rack: https://spin.atomicobject.com/2012/07/11/get-and-post-parameter-parsing-in-rails-2/

I don't fully understand this stuff myself, but can you try something like:
```
    assert TestParams.new(foo: { "bar[]" => { baz: 'foobar' } }).valid?
```

**Comment by TiteiKo** [comment]
I was trying to debug this stuff, and it looks like master branch resolves the issue, thanks to this commit: https://github.com/hanami/controller/commit/df6224080b247784bffecca0d382918c7d22267b

So yay! :) (and sorry for all the fuss)
