### ISSUE TITLE
How to use custom predicates for params

### ISSUE THREAD

**Issue by thhermansen** [hanami/controller#178]
Hi,

I have tried to figure this one out on my own, but I'm unable to make it work.

What I want to do is to define custom predicates like `:uuid?` which is usable within the definition of params in a controller, like this:

``` ruby
params do
  required(:id).filled :uuid?
end
```

I have managed to get this working both with [dry-validation directly](http://dry-rb.org/gems/dry-validation/custom-predicates/) and with hanami-validation [global custom predicates example](https://github.com/hanami/validations#global-custom-predicates), but I'm unable to make the `:uuid?` predicate available in the context of a controller.

I have tried include a module to the controller, and I have tried to drop down to dry-validation and [configure my predicate globally](https://github.com/dry-rb/dry-validation/issues/122).

Is there an easy way of doing this which I have missed? Thank you!

**Comment by AlfonsoUceda** [comment]
Hi @thhermansen, do you still have this issue? are you using hanami controller alone or a full hanami app?

**Comment by thhermansen** [comment]
Hi, and thank you for answering. I didn't figure it out so the question is still valid.  We are using controllers in a full Hanami app.

**Comment by TiteiKo** [comment]
Hi @thhermansen 

You can either have the predicates in a module:

```ruby
module UuidPredicate
  include Hanami::Validations::Predicates

  predicate(:uuid?) do |value|
    value == 'foo'
  end
end


params do
  predicates UuidPredicate
  required(:id).filled(:uuid?)
end
```

Or declare the predicate directly in your `params` block:

```ruby
params do
  configure do
    def uuid?(value)
      value == 'foo'
    end
  end

  required(:id).filled(:uuid?)
end 
```

**Comment by thhermansen** [comment]
Thank you! I'll try it out.

**Comment by jodosha** [comment]
@thhermansen Please let us to know if it works for you. Thanks! 👍
