### ISSUE TITLE
Ability to prepend middlewares.

### ISSUE THREAD

**Issue by beauby** [hanami/controller#182]
Currently there does not seem to be a possibility to add a middleware at the bottom of the stack (i.e. so that it runs _before_ the stock hanami ones), let alone *before* or *after* (or even *replacing*) a given one.

`Rack::Builder` does not seem to provide an interface to do that (rails, for instance, handles its own middleware stack).

IMO this would be a nice feature to have. Thoughts?

Edit: I'm actually not sure about the inability to *prepend* (though if I'm wrong, then it's not possible to *append* middlewares). The reason why I initially thought so was because parameter parsing has already happened when the middleware is ran.

**Comment by jodosha** [comment]
@beauby Hi. Are you talking about middleware stack in a single action?

**Comment by beauby** [comment]
@jodosha Yes, exactly. I'm not 100% confident with the whole router/controller/rack dance yet though, so I may be mistaken.

**Comment by jodosha** [comment]
@beauby Interesting, what's your specific use case?

**Comment by jodosha** [comment]
@beauby To recap:

  * For a Hanami project, you can `use` middleware before Hanami stack in `config.ru`
  * For a single Hanami application, you can use `middleware.prepend`. See https://github.com/hanami/hanami/blob/6e80d339e97b67563c75daa5b2b6cf4d4bceffd8/lib/hanami/middleware.rb#L82
  * For a single action, there is no way to prepend, only `use` to add a new middleware. Here you should have the ability to control the order.
