### ISSUE TITLE
Consider moving parameters merging from router to controller.

### ISSUE THREAD

**Issue by beauby** [hanami/controller#183]
# Current behavior

Currently, the router takes care of parsing the request body, symbolizing its keys, and merging it into `env[routers.params]`. Then, the controller action uses it to build its `params` hash that is passed to `Action#call` (it actually merges it into `Rack::Request.new(env).params`, which is the union of GET and POST params (though the latter would be empty when receiving JSON)).

# Questions
1. Considering that either the POST data is not JSON, in which case `Rack::Request.new(env).params` will contain the POST data, but `env['router.params']` as well, or the POST data is JSON, in which case `Rack::Request.new(env).params` will just be the GET parameters, why not simply merge `env['router.params']` into `Rack::Request.new(env).GET`?

2. Why merge the router params, the query params, and the post params early (in the router)? Merging it later would allow people to use middleware to modify the POST/GET data independently without causing weird behavior with `Action#params`.

# Suggestion

Keep the router params in `env['router.path_params']`, keep the body params in `env['router.parsed_body']`, and keep the GET params in `env['router.query_params']`, and do not symbolize any before hitting the controller (basically do the symbolizing + merging in `BaseParams#initialize`).

**Comment by joneslee85** [comment]
cc @hanami/core-team

**Comment by joneslee85** [comment]
@beauby thanks for the questions. The answer on why router is now handing the params merger responsibility, I'd leave it to @jodosha. I think his idea is a ready-to-go routing component that could be hooked into any application. Having to depend on hanami-controller or writing their own pre-processing code in non-hanami apps seems a bit inconvenient.

Having said that, I would like to know any specific use case that you run into and what stops you from adding extra middleware to dup and post-process `params`? In fact, if the biz requires more deep level customisation, the raw params is always there if needed.

**Comment by beauby** [comment]
> Having to depend on hanami-controller or writing their own pre-processing code in non-hanami apps seems a bit inconvenient.

Currently they would have to write the same current preprocessing code that is in [Hanami::Action::BaseParams](https://github.com/hanami/controller/blob/master/lib/hanami/action/base_params.rb#L134), that is
```ruby
result = {}
result.merge! ::Rack::Request.new(env).params  # merge the GET and POST params
result.merge! _router_params  # merge the path params (controller and action) AND the POST params
```
What I'm suggesting would change what they'd have to write to
```ruby
result = {}
result.merge! ::Rack::Request.new(env).GET  # merge the GET ~~and POST params~~
result.merge! _body_params  # merge the body params
result.merge! _router_params  # merge the path params (controller and action) ~~AND the POST params~~
```

Basically, I think it should be up to the controller layer how to expose each kind of parameter.

The exact situation I am facing is that I am deserializing a [JSON API](http://jsonapi.org) payload in the request body, so I would like to **replace the body** with the deserialized hash, and have it available to the controller action as normal input, **without remnants from the non-deserialized payload**. Currently I'm achieving that by:

+ deserializing data from `env['router.parsed_body']`
+ removing all `env['router.parsed_body'].keys` from `env['router.params']`
+ adding my deserialized hash to `env['router.params']`.

The issue being that, since the merging of body params into router params has already happened when the deserialization middleware kicks in, modifying `env['router.parsed_body']` will have no effect on the params of the action.

**Comment by thhermansen** [comment]
> The exact situation I am facing is that I am deserializing a JSON API payload in the request body, so I would like to replace the body with the deserialized hash, and have it available to the controller action as normal input, without remnants from the non-deserialized payload. 

I don't know if it helps or not. Please disregard this post if it's off topic: I solved the same JSON API dasherized-to-underscore situation by creating a JSON body parser which I used instead of Hanami's default JSON body parser.

So in the `Hanami::Application configure` block I did
```ruby
body_parsers JsonParserUnderscoredKeys.new
```

Where JsonParserUnderscoredKeys looks something like:
```ruby
class JsonParserUnderscoredKeys < Hanami::Routing::Parsing::JsonParser
  def parse(body)
    MyApp::Utils::Hash.new(super).deep_transform_keys do |key|
      Hanami::Utils::String.new(key).underscore.to_s
    end.to_h
  end
end
```

**Comment by beauby** [comment]
@thhermansen The issue with having a custom body parser is that it cannot be parametrized from the controller action (which is needed in my case to tell the difference between a resource creation/update payload, or a relationship update payload – those two having slightly different grammars per the spec).

**Comment by thhermansen** [comment]
Oki, I understand. We used the custom body parser with Ember data json API adapter which worked fine both for create/update and read, but there may be some detail in the JSON API spec which I'm not familiar with.

(We are actually experimenting with [GraphQL](https://github.com/rmosolgo/graphql-ruby) due to inconsistency between our [server side rendered JSON API response](https://github.com/fotinakis/jsonapi-serializers), ember data JSON api adapter and the JSON API spec itself. Unfortunately we found these three not always to be in sync.)

**Comment by jodosha** [comment]
@beauby Hi, what if you mount a rack middleware in `config.ru` of a Hanami project?

```ruby
# config.ru
require './config/environment'

use CustomParser
run Hanami.app
```

**Comment by beauby** [comment]
@jodosha The issue with that is the same: it cannot be parametrized per-action (except if one reimplements parts of the router in the middleware, but that sucks).

The goal here is that one could:
1. [x] call `use` from within an `Action` class,
2. [x] have the loaded middleware modify the parsed body, and finally
3. [ ] have the modified parsed body accessible through `params`.

Currently, 1 and 2 are possible, but the fact that the action `params` are aggregated directly in the router makes it so that modifications on the parsed body will have no effect on the `params`.

**Comment by jodosha** [comment]
This modification makes sense, but it requires a major rework of `hanami-controller` and `hanami-router`, which we can't do now. The reason is to reach 1.0 ASAP. @beauby I'm sorry about that.
