### ISSUE TITLE
[Discussion] Add information how to render view

### ISSUE THREAD

**Issue by davydovanton** [hanami/controller#190]
I have hanami app with the create action. I tried to render the new view with 422 status code (like in guides) but instead that I saw error page. After that I found that I can render specific view using this code:
```ruby
def call(params)
  if params.valid?
    # ...
  else
    self.body = Web::Views::Tasks::New.render(format: format, params: params)
  end
end
```

And now all works fine for me.

That's why I have a question: maybe is better to add this information to guides and update starting guide?

/cc @hanami/contributors @hanami/core-team

**Comment by cllns** [comment]
Did you [add `template 'books/new'` to the View](https://github.com/hanami/hanami.github.io/blame/build/source/guides/getting-started.md#L904)? 

Or is the issue that you want the whole `New` view to render, rather than just that template?

**Comment by beauby** [comment]
@cllns I think the "issue" is that if you explicitly set the status to a non-success one (like `422`), the view is bypassed.

**Comment by mereghost** [comment]
@davydovanton How were you setting the response code? If you were using the `status(code, message)` helper the rendering will be bypassed as it sets the body to `message`.

If you set `self.status` directly, the rendering will not (should not) be bypassed.

**Comment by jodosha** [comment]
@davydovanton Hi, this should help to solve your problem. http://hanamirb.org/guides/actions/control-flow/#http-status
