### ISSUE TITLE
Custom validation predicates

### ISSUE THREAD

**Issue by kaikuchn** [hanami/controller#209]
Greetings,

I've been trying to define a custom predicate to validate a parameter in one of my controllers. ~~So far I have been unable to figure out how to accomplish this.~~ After asking in gitter about how to accomplish this, @jodosha said that [it isn't possible right now](https://gitter.im/hanami/chat?at=589b50faaa800ee52c6c0a5e).

[Here's a gist](https://gist.github.com/kaikuchn/bdcd08e50cf073c50082407c38912e3b) of what I'd like to be able to do.
Is it just me, or is this something others would like to have too? Thoughts on that?

I'd be willing to try and come up with a PR if this is a feature that you'd like to provide.

UPDATE: Figured out how to do this in a way that does not register predicates globally. See https://github.com/hanami/controller/issues/209#issuecomment-279328274

**Comment by kaikuchn** [comment]
Ah, btw. this is possible right now, it just breaks when using schema due to https://github.com/hanami/validations/issues/123:
```ruby
# frozen_string_literal: true
Hanami::Action::Params.predicate(:valid_criterion?, message: 'foo') do |criterion|
  AlertCriterion::Notation.validate(criterion).success?
end

module Web::Controllers::Alerts
  class Create
    include Web::Action

    params do
      required(:alert).schema do
        required(:topic).filled(:str?)
        required(:criterion) { filled? & str? & valid_criterion? }
        required(:action).filled(:str?)
      end
    end

    def call(params)
      if params.valid?
        repo = AlertRuleRepo.new
        repo.create(params.get(:alert))
        redirect_to routes.notifications_alerts_path
      else
        self.status = 400
      end
    end
  end
end
```

This then registers the custom predicate in the global predicate registry, even for other containers I guess.

**Comment by kaikuchn** [comment]
Okay, so on master the above works, but it registers the predicate globally (in `Web::Action::Params` registry). However, it is also possible to call `predicate` on `Web::Controllers::Alerts::Create::Params` which then registers the custom predicate only for that action.

I.e., it is possible, it just isn't documents and not part of the public API.

**Comment by jodosha** [comment]
@kaikuchn Hey, well it's possible because with Ruby everything is possible 😉 .

It doesn't work inside `params` because we pass that block directly to `Hanami::Validations.validations`, which doesn't take account of inline predicates.

Anyway, I think we can make this to work.

**Comment by kbaba1001** [comment]
I did as follows.

define `apps/web/validations/base.rb`, next.

```ruby
module Web::Validations
  class Base < Hanami::Action::Params
    predicate(:valid_criterion?, message: 'foo') do |criterion|
      AlertCriterion::Notation.validate(criterion).success?
    end
  end
end
```

in, `apps/web/application.rb`

```ruby
  # ...
  load_paths << [
    'validations', # add
    'controllers',
    'views'
  ]
  # ...
```

```ruby
module Web::Controllers::Alerts
  class Create
    include Web::Action

    params Class.new(Web::Validations::Base) do
      validations do
        required(:alert).schema do
          required(:criterion) { filled? & str? & valid_criterion? }
        end
      end
    end

    def call(params)
      # ...
    end
  end
end
```

**Comment by jodosha** [comment]
I tried to integrate this feature on today, but it wasn't possible.

The block accepted by `Hanami::Action::Params.params`, is yielded by `Hanami::Validations.validations`. This last method is designed to decorate and forward the block to build `Dry::Validation::Schema` (or `Dry::Validation::Form`).

That means any other feature from `hanami-validation` cannot be applied in the context of the `params`, if a block is passed.

---

The way that @kbaba1001 suggests, is to create a "base class" for params. The problem with that approach is that the predicate that supposed to be available only in a single context (where it's "inlined"), it's available to the entire `Web` namespace.

---

There is a way to have inline predicates **and** not pollute the entire `Web` namespace with a predicate:

```ruby
module Web::Controllers::Books
  class Create
    include Web::Action

    params Class.new(Hanami::Action::Params) {
      predicate(:cool?, message: "is not cool") do |current|
        current.match(/cool/)
      end

      validations do
        required(:book).schema do
          required(:title) { filled? & str? & cool? }
        end
      end
    }

    def call(params)
      if params.valid?
        self.body = 'OK'
      else
        self.body = params.error_messages.join("\n")
      end
    end
  end
end
```

By using a `Hanami::Action::Params` subclass we're able to access all the features from `hanami-validations`. The only "price to pay" is to wrap the schema inside the `validations` block.

---

Documented by https://github.com/hanami/hanami.github.io/commit/0e93ec568acb1acdc052e64bb1f11a38c34dbcc6
