### ISSUE TITLE
Regression: flash after redirect broken

### ISSUE THREAD

**Issue by cllns** [hanami/controller#213]
Flash messages should survive after a redirect. They used to with `0.9.2`, but now they don't, with `1.0.0.beta1`. 

This is a result from #202. Specifically, [the change to the implementation of `_values` in `lib/hanami/action/flash.rb`](https://github.com/hanami/controller/pull/202/files#diff-ce13f23d4ed57d06a91f48c61b42c054L145). I reverted that one line locally and flashes survive redirects.

Note: that line should not just be reverted, since we should still address #196.

Discovered in parallel (and simultaneously!) by @deangerber. I think someone else mentioned this recently too, but I can't find who it was.

**Comment by cllns** [comment]
The test added for that change seems to address this. I'm not sure what's different between my local code and that test 🤔

**Comment by cllns** [comment]
So it seems like the test is memoizing the flash value in the header. After the flash is stored into the header, it's wiped out.

**Comment by mereghost** [comment]
@cllns I think the test was done this way as sessions are not enabled by default (and are a pain to test with).
