### ISSUE TITLE
Sending file from an IO Buffer

### ISSUE THREAD

**Issue by aarondufall** [hanami/controller#223]
Is it possible to send a file directly from an IO Buffer?

I know `#send_file` doesn't support this behavior, but this is what I'm trying to do.

Example:

```
s3 = Aws::S3::Resource.new(region: region)
obj = s3.bucket(bucket).object(key)
send_file obj.get.body
```

**Comment by jodosha** [comment]
@aarondufall We don't support it yet.

What happens if you do one of the following things?

```ruby
self.body = obj.get
```

or

```ruby
self.body = obj.get.body
```

Thank you.

**Comment by aarondufall** [comment]
Thanks @jodosha that works fine 👍
