### ISSUE TITLE
Deep symbolization of params with nested array of hashes

### ISSUE THREAD

**Issue by rybex** [hanami/controller#234]
Hi,

Hanami uses the `Hanami::Utils::Hash` to parse controller's params which doesn't symbolize nested array of hashes. IMHO we should symbolize them to keep consistency. I have prepared small [PR](https://github.com/hanami/utils/pull/232) in the Hanami utils lib to fix it. Does it make any sense?

**Comment by jodosha** [comment]
@rybex Would you mind to use `Hanami::Utils::Hash.deep_symbolize` instead of `#symbolize!`. Thanks.

---

I'm closing this because of: https://github.com/hanami/utils/pull/232#issuecomment-333568195
