### ISSUE TITLE
Action params incompatibility with hanami/model

### ISSUE THREAD

**Issue by 7even** [hanami/controller#235]
Hi.

It seems like `Hanami::Action::BaseParams` is not really compatible with the `has_many` association in hanami/model. When I pass `params` in my action to the repository method that creates both a parent object and it's child objects I get a `Hanami::Model::Error: undefined method 'reject' for #<Web::Controllers::Authors::Create::Params:0x00007ff722746ff0>`.

It seems like this can be fixed by including `Enumerable` in `Hanami::Action::BaseParams` - it already implements [#each](https://github.com/hanami/controller/blob/master/lib/hanami/action/base_params.rb#L137-L139) - but I didn't try.

I reproduced the problem in my fork of the bookshelf application:

* [action](https://github.com/7even/bookshelf/blob/nested-param/apps/web/controllers/authors/create.rb#L18)
* [repository method that fails](https://github.com/7even/bookshelf/blob/nested-param/lib/bookshelf/repositories/author_repository.rb#L14-L16)
* [action spec](https://github.com/7even/bookshelf/blob/nested-param/spec/web/controllers/authors/create_spec.rb)

Here's the error:

```
$ ruby spec/web/controllers/authors/create_spec.rb

Run options: --seed 33521

# Running:

E

Finished in 0.011752s, 85.0919 runs/s, 0.0000 assertions/s.

  1) Error:
Web::Controllers::Authors::Create#test_0001_creates an Author:
Hanami::Model::Error: undefined method `reject' for #<Web::Controllers::Authors::Create::Params:0x00007ff722746ff0>
    /Users/7even/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/hanami-model-1.1.0.beta3/lib/hanami/model/associations/has_many.rb:55:in `rescue in create'
    /Users/7even/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/hanami-model-1.1.0.beta3/lib/hanami/model/associations/has_many.rb:52:in `create'
    /Users/7even/projects/bookshelf/lib/bookshelf/repositories/author_repository.rb:15:in `create_with_books'
    /Users/7even/projects/bookshelf/apps/web/controllers/authors/create.rb:18:in `call'
    /Users/7even/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/hanami-controller-1.1.0.beta3/lib/hanami/action/callbacks.rb:195:in `call'
    /Users/7even/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/hanami-controller-1.1.0.beta3/lib/hanami/action/callable.rb:71:in `block in call'
    /Users/7even/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/hanami-controller-1.1.0.beta3/lib/hanami/action/throwable.rb:145:in `block in _rescue'
    /Users/7even/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/hanami-controller-1.1.0.beta3/lib/hanami/action/throwable.rb:143:in `catch'
    /Users/7even/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/hanami-controller-1.1.0.beta3/lib/hanami/action/throwable.rb:143:in `_rescue'
    /Users/7even/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/hanami-controller-1.1.0.beta3/lib/hanami/action/callable.rb:67:in `call'
    spec/web/controllers/authors/create_spec.rb:16:in `block (2 levels) in <main>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

My current workaround is adding `.to_h` to `params` but I think params could behave as a real enumerable to avoid these little hacks.

**Comment by jodosha** [comment]
@7even Hi and thanks for reporting this problem.

> My current workaround is adding .to_h to params but I think params could behave as a real enumerable to avoid these little hacks.

I don't agree.

As of Hanami 1.1.0, `Params` will have 12 public methods:

```ruby
(byebug) params.methods - Object.new.methods
[:to_hash, :to_h, :valid?, :error_messages, :errors, :raw, :validate, :[], :each, :dig, :env, :get]
(byebug) (params.methods - Object.new.methods).count
12
```

If we include `Enumerable` we would have 67 public methods:

```ruby
(byebug) params.methods - Object.new.methods
[:to_hash, :to_h, :valid?, :error_messages, :errors, :raw, :max, :min, :to_a, :include?, :find, :entries, :sort, :sort_by, :grep, :grep_v, :count, :detect, :find_index, :find_all, :select, :reject, :collect, :map, :flat_map, :collect_concat, :inject, :reduce, :partition, :group_by, :first, :all?, :any?, :one?, :none?, :minmax, :min_by, :max_by, :minmax_by, :member?, :each_with_index, :reverse_each, :each_entry, :each_slice, :each_cons, :each_with_object, :zip, :take, :take_while, :drop, :drop_while, :cycle, :chunk, :slice_before, :slice_after, :slice_when, :chunk_while, :sum, :uniq, :lazy, :to_set, :validate, :[], :each, :dig, :env, :get]
(byebug) (params.methods - Object.new.methods).count
67
```

67 implicit, non-tested public methods. This is why apps breaks during their lifetime.
Considering Params as an enumerable is conceptually wrong (sort of Primitive Obsession), and it leads to tight coupling between layers.

If you're interested in a deeper opinion on this, please read:

  * https://lucaguidi.com/2014/06/09/three-things-to-know-about-composition/
  * https://blog.dnsimple.com/2016/10/overcoming-primitive-obsession/
  * https://blog.dnsimple.com/2016/11/purposes-and-properties-of-value-objects/
  * https://blog.dnsimple.com/2016/12/ruby-coercion-protocols-part-1/
  * https://blog.dnsimple.com/2017/01/ruby-coercion-protocols-part-2/

---

It's better to use Ruby Coercion Protocols to serialize during the communication between layers.

My proposal is: `hanami-model` API should serialize (via `#to_hash`) an received before to operate on it.

This has several advantages:

  * It's open for extension: anything that respond to `#to_hash` is compatible with `hanami-model`
  * It already works with existing components: entities, params, Ruby's `::Hash`
  * It avoids tight coupling between `hanami-controller` and `hanami-model`
  * It allows you to still pass down params from actions: `AuthorRepository.new.create_with_books(params)` will work

**Comment by 7even** [comment]
@jodosha thank you for such a detailed answer.

Yeah, I see your point. Although I wouldn't say these 67 methods are non-tested given that the `#each` method is tested, and all `Enumerable` methods solely rely on it - but using input coercion definitely should reduce coupling and make public interface of repositories more universal. 

Should I close this issue and open it in `hanami-model` then?

**Comment by jodosha** [comment]
Implemented by https://github.com/hanami/model/pull/462
