### ISSUE TITLE
It's not possible to iterate Hanami::Action::CookieJar

### ISSUE THREAD

**Issue by graywolf** [hanami/controller#238]
When I want to know what cookies are set, I tried

    cookies.each { |k, v| ... }

but got

    NoMethodError: undefined method `each' for #<Hanami::Action::CookieJar:0x00007f63a1477488>

Is there a technical reason why `CookieJar` doesn't have `#each` or is it just oversight?

**Comment by jodosha** [comment]
@graywolf We're conservative with the public API: only the methods that we recognize as useful are carefully added one by one. Your request makes sense.

This approach helps us to maintain the bare minimum set of methods that are actually useful to people.

I've implemented this enhancement with #239 and it will be released with Hanami `v1.1.0`.

**Comment by jodosha** [comment]
Implemented by https://github.com/hanami/controller/pull/239
