### ISSUE TITLE
How to supply the request body when testing a PUT action?

### ISSUE THREAD

**Issue by thoiberg** [hanami/controller#249]
Hi, I've got a question around unit testing the request body for PUT/POST endpoints in Hanami. I've got a PUT action that takes the body from the request and forwards it on to another system in the interwebs and I can't figure out how to supply the `request.body` to the action command.

Source code:
```ruby
def call(params)
  params do
    required(:author_uuid).filled
  end

  url = "url/to/other/endpoint"

  put_params = {
    photo_uuids: json_request_body['itemIds'],
    update_data: json_request_body['updateData'],
  }
  
  OtherSystemApiClient.put(url, put_params)
end

def json_request_body
  @json_request_body ||= JSON.parse(request.body.read)
end
```

Test code:
```ruby
require_relative 'item_update'

RSpec.describe Items::Update do

  let(:action) { described_class.new }
  let(:params) { Hash['rack.session' => {user: user, last_sign_in: last_sign_in}] }
  let(:user) { ::Authentication::User.new(username: 'xyz') }
  let(:last_sign_in) { Time.now }

  context 'when a user is present in the parameters' do
    it 'forwards the data to the other endpoint' do
      expect(OtherSystemApiClient).to receive(:put)

      action.call(params)
    end
  end
end
```

This is failing when I run the tests because the `request.body` method is `nil`.

 I looked through the [action testing guide](http://hanamirb.org/guides/1.0/actions/testing/) but it only uses GET requests as an example, and I couldn't find anything on the internet so I was hoping someone could help me 🙏 .

**Comment by AlfonsoUceda** [comment]
Hi @thoiberg

Do you have a template? if not you can bypass templates using the following line:
```ruby
self.body = OtherSystemApiClient.put(url, put_params)
```
can you tell me if this works?

**Comment by AlfonsoUceda** [comment]
@thoiberg did it work for you?

**Comment by jodosha** [comment]
@thoiberg During the tests, anything that is passed to `Action#call` is interpreted as the Rack env. The `request` object is a `Hanami::Action::Request`, which inherits from `Rack::Request`: for its body it requires a `"rack.input"` key to be an `IO` object.

To recap:

```ruby
let(:params) { Hash['rack.session' => {user: user, last_sign_in: last_sign_in}, 'rack.input' => StringIO.new("...")] }
```

**Comment by thoiberg** [comment]
Sorry I asked the question and then _totally_ forgot about it 😅. Setting `rack.input` on the params object has worked for me, thank you very much @AlfonsoUceda and @jodosha 🙇
