### ISSUE TITLE
Remove body cleanup for HEAD HTTP requests

### ISSUE THREAD

**Issue by jodosha** [hanami/controller#253]
`Hanami::Action` 1.x empties the body if the HTTP request is using HEAD verb.

While this is formally correct, and makes the action "full featured", we have the same control in `hanami-router` and `hanami`. This makes a total of three times for each request. The idea is to use `Rack::Head` from `rack` gem instead of these custom controls.

Developers who are using `hanami-controller` as standalone gem, can mount that middleware.
Developers who are using `hanami` don't need to take any action, because we'll mount that middleware at the project level.

---

This change **MUST** go to `unstable` branch.

---

Ref https://github.com/hanami/router/issues/164
Ref https://trello.com/c/fQw5F4Hp

**Comment by GustavoCaso** [comment]
Closed by #263
