### ISSUE TITLE
Remove `Hanami::Action#parsed_request_body`

### ISSUE THREAD

**Issue by jodosha** [hanami/controller#255]
`Hanami::Action#parsed_request_body` is deprecated in 1.3 and should be removed in 2.0.

---

This change **MUST** go to the `unstable` branch.

**NOTE:** Due to the changes that `unstable` branch contains `Hanami::Action#parsed_request_body` is referenced as `Hanami::Action::Request#parsed_body`. This is the method to be removed.

---

Ref https://github.com/hanami/controller/issues/254
Ref https://github.com/hanami/router/issues/163

**Comment by GustavoCaso** [comment]
Closed by #261
