### ISSUE TITLE
Make `Hanami::Action::{Request,Response}` `#session` and `#flash` to raise `Hanami::Controller::MissingSessionError` when session is not configured

### ISSUE THREAD

**Issue by jodosha** [hanami/controller#256]
With https://github.com/hanami/controller/pull/250 (v1.2.0) we introduced a new exception (`Hanami::Controller::MissingSessionError`) which is raised when a dev tries to access `Action#session` and `Action#flash` when the HTTP session isn't configured.

In 2.0 (`unstable` branch), the access to `session` and `flash` will be moved from `Hanami::Action` to `Hanami::Action::Request` and `Response`. These two objects need to support the old behavior of raising a `Hanami::Controller::MissingSessionError`.

---

This change **IS** for `unstable` branch.

---

Ref https://github.com/hanami/controller/pull/250

**Comment by GustavoCaso** [comment]
Sorry, that was a wrong click 😄

**Comment by timriley** [comment]
Fixed in #379.
