### ISSUE TITLE
Rename `Hanami::Action.content_type` into `.accept`

### ISSUE THREAD

**Issue by jodosha** [hanami/controller#257]
With https://github.com/hanami/controller/pull/247 (v1.2.0) we introduced `Hanami::Action.content_type` which is a DSL that restrict the access based on request's `Content-Type` of the payload and halt with `415 Unsupported Media Type` in case of mismatch.

On the other hand we already had `.accept` (v0.1.0), which was built to do the exact same thing, but it targets `Accept` header instead.

To recap: the actual `Hanami::Action.content_type` has the **right** implementation, but it should be named `.accept` instead.

```ruby
class MyAction < Hanami::Action
  accept :json

  def call(*)
    # ...
  end
end
```

This will let to pass only the requests that have a matching `Content-Type` header.

---

This change **MUST** go to `unstable` branch.

---

Ref https://github.com/hanami/controller/pull/247
Ref https://github.com/hanami/controller/commit/fd9e0808ff5fe6798836d9e9b7cab20267383b18

**Comment by timriley** [comment]
Thanks @tak1n, closing this now :)
