### ISSUE TITLE
Remove body cleanup for HTTP responses that doesn't require a body (e.g. 204)

### ISSUE THREAD

**Issue by jodosha** [hanami/controller#264]
`Hanami::Action` 1.x empties the body if the HTTP response doesn't require a body (e.g. 204).

While this is formally correct, and makes the action "full featured", we have the same control in `hanami-router` and `hanami`. This makes a total of three times for each request. The idea is to give responsibility to developers to produce a compliant HTTP response, or to use a Rack middleware to ensure this correctness.

---

This change **MUST** go to `unstable` branch.

---

Ref https://github.com/hanami/controller/issues/253
Ref https://github.com/hanami/router/issues/164
Ref https://trello.com/c/fQw5F4Hp

**Comment by GustavoCaso** [comment]
Closed by https://github.com/hanami/controller/pull/268
