### ISSUE TITLE
Flash #empty? returns true when it's not (after a re-direct)

### ISSUE THREAD

**Issue by cllns** [hanami/controller#266]
Here's an example app illustrating the problem: https://github.com/cllns/flash-error-example-app

If you visit `/books`, you're redirected to `/home` and you'll see this rendered (from both the layout template and view template:

```
Value of flash[:info]: Books are gone! Go home!

Value of flash.empty?: true 
```
Empty should not be true if there are values in the flash.

I tried to figure this out for a couple hours and I'm stuck.

I added some debugging statements to `Hanami::Action::Flash#empty?` and it shows the following:

```
16:43:01 web.1  | #<Hanami::Action::Flash:0x7f9f299a0130 {:success=>"You have been signed out 👍"}>
16:43:01 web.1  | #empty? body definition
16:43:01 web.1  | _values: [{}]
16:43:01 web.1  | @merged: {:success=>"You have been signed out 👍"}
16:43:01 web.1  | Empty?: true
```
If I change the return value from `#empty?` to `_values.all?(&:empty?)) && @merged.empty?` then it works (since _values isn't being synced with @merged) in a way I'd expect it to. This does not break any specs, but I can't figure out the issue so that I could write a spec that fails without that change.

I'm not 100% sure this is a bug with `hanami-controller`, but I think it is. Specifically, I think it has something to do with the view being rendered after the controller has called `#finish`?

**Comment by jodosha** [comment]
@cllns Can you please take care of this? Thanks.

**Comment by GustavoCaso** [comment]
Fixed in https://github.com/hanami/controller/pull/267
