### ISSUE TITLE
Hanami::Action::Flash to use swappable JSON backend

### ISSUE THREAD

**Issue by jodosha** [hanami/controller#273]
As of `hanami-utils` `v0.8.0` we [introduced](https://github.com/hanami/utils/blob/master/CHANGELOG.md#v080---2016-07-22) `Hanami::Utils::Json`, which is a module that abstracts JSON backends.

It would be great if `Hanami::Action::Flash` would use it for JSON serialization, instead of going directly to Ruby stdlib `JSON` module.

---

Ref https://github.com/hanami/utils/pull/142
Ref https://github.com/hanami/controller/pull/272

**Comment by GustavoCaso** [comment]
@jodosha I can take care of this one

**Comment by GustavoCaso** [comment]
Fixed in #275
