### ISSUE TITLE
Exception Handling in Production

### ISSUE THREAD

**Issue by mcansky** [hanami/controller#287]
While documentation describes how to add custom exception handling, I had trouble figuring out why and how to get exceptions from a Redis call to be caught properly by the custom exception handler in the controller using the entity where the call happens.
So far my only success was in adding a rescue block in the entity at the specific place where I would need it. That feels odd to me, but I might be wrong.

The general goal for me is to have my hanami apps report all exceptions to a Sentry instance through the raven gem.
Since the production setup in hanami handles all exception, I am looking for a way to have a simple setup for things like Raven/Sentry to track exceptions in hanami apps.

Any comments on best practice for this would be greatly appreciated.

**Comment by kaikuchn** [comment]
There's a snippet in the making that may be just what you need: https://github.com/hanami/snippets/pull/10

**Comment by jodosha** [comment]
@mcansky I'm sorry about the confusion. I see two problems here: 1. the expectations regarding this feature 2. how to make it work.

---

Let me first clarify the goal of _exception handling_ feature. It's meant to catch an exception and turn it into a HTTP error status (usually 4xx). Because it's managed (aka expected), you usually don't want to report it to Sentry, but sent unmanaged (aka unexpected) exceptions instead.

This is the typical usage of the feature. If you still want to send to Sentry all the exceptions, even the ones caught via `handle_exception`, I suggest to have a look at this paragraph: https://guides.hanamirb.org/actions/exception-handling/#custom-handlers

Via a custom handler you can manually send exceptions to Sentry: https://docs.sentry.io/clients/ruby/#reporting-failures

```ruby
class MyAction
  include Hanami::Action
  handle_exception FooError => :handle_foo_error

  def call(params)
    # ...
  end

  private

  def handle_foo_error(exception)
    Raven.capture_exception(exception)
    status 400, exception.message
  end
end
```

If you need to handle `FooError` across all the actions, you can share the handling like this: https://guides.hanamirb.org/actions/share-code/

---

Now getting back to your exception raised from Redis. How's your code looking like?

**Comment by mcansky** [comment]
thanks both for your answer, I think indeed there is a bit of confusion about what we all mean and expect.

Let me take a clearer example.

Let's say we add a feature that does some work with an API, pull some data in as JSON, unmarshall it into objects and .. boom, for some reason the data in the JSON isn't as expected and an exception is raised because the code was never meant to handle this case (yet).

So yes, that refers to unmanaged exceptions.
I have tried adding a module and using the application configuration to get all the actions to include a custom method to call with `handle_exception StandardError => :handle_errors` but that's to no avail. Exceptions happening don't bubble up and I am still left with a 500.

So I guess my issue is more with making sure exceptions triggered through an action and within methods and libs called by the actions do bubble up to Sentry for triage, inspection, and fix.

here is the extract from `apps/web/application.rb`

```
controller.prepare do
        include RavenHanami

        handle_exception StandardError => :capture_exception
end
```

and the module :

```
module RavenHanami
  private
  def capture_exception(exception)
    LOGGER.info("!!!!! EXCEPTION Caught for Raven/Sentry !!!!!")
    Raven.capture_exception(exception)
    redirect_to '/'
  end
end
```

is there something missing ?

**Comment by kaikuchn** [comment]
I'm confused about this:

> Exceptions happening don't bubble up and I am still left with a 500.

If the exception does not bubble up, then it must be handled by someone and you would not get a 500. The fact that you get a 500 page shows, that Hanami is handling the exception at the controller level.
It just seems like your customer handler is not triggered..
But your code looks fine. Maybe the exception you're raising isn't a kind of `StandardError`?

configure :development do
      # Don't handle exceptions in development, render the stack trace
      handle_exceptions false
    end

**Comment by mcansky** [comment]
@kaikuchn : most exceptions in Ruby and its frameworks are inheriting from StandardError afaik, so that should go ok (I suppose ?).

I will do another round of checks ... and report back.

**Comment by jodosha** [comment]
@mcansky 👋 any news on this?

**Comment by DangerDawson** [comment]
@mcansky Did you manage to solve this?

**Comment by kaikuchn** [comment]
@DangerDawson do you have the same problem?

**Comment by DangerDawson** [comment]
I noticed that we were getting 500 errors, and not receiving any Honeybadger notifications for certain scenario’s in production.

I plan to look into this later this week and see if I can pin point the problem, and report back.

**Comment by mcansky** [comment]
apologies everyone it looks like I moved on into another project and could not report back;

**Comment by DangerDawson** [comment]
So I have got to the bottom of what is happening, any exceptions being raised in the controller produces both a stack_trace and send the exception message to HoneyBadger, although if the exception happens in the view object it does not.

Is this expected behaviour?

**Comment by kaikuchn** [comment]
Docs say this:

> Handle the given exception with an HTTP status code.
>
> When the exception is raise during #call execution, it will be
> translated into the associated HTTP status.

However, as can be seen in [Callable](https://github.com/hanami/controller/blob/master/lib/hanami/action/callable.rb#L66) the Rack response is prepared outside of the rescue block. And the result of `#call` is then passed into the renderer.
I.e., the view is rendered only after the action finished executing. (See [here](https://github.com/hanami/hanami/blob/master/lib/hanami/application.rb#L169), `middleware` would be the action in most cases.)

**Comment by DangerDawson** [comment]
So it looks as though this PR [#866](https://github.com/hanami/hanami/pull/866) is responsible for the behaviour I am witnessing, specifically this [line](https://github.com/hanami/hanami/blob/09d28ac432d73436481c023dd59b84ce9c6b58d1/lib/hanami/rendering_policy.rb#L61).

I managed to solve my specific issue by inserting the HoneyBadger middleware in my `config.ru`

```
require './config/environment'

use Honeybadger::Rack::ErrorNotifier
run Hanami.app
```

Although I still find the behaviour confusing that exceptions in the view are handled differently from those that manifest in the controller / services / etc.

**Comment by DangerDawson** [comment]
Any update on this? 

Although I am able to receive exceptions in Honeybadger, I do not have any context, and the logs do not provide any stacktrace either.

Like I said, this is completely different behaviour from any exceptions happening before the view rendering e.g. services / controllers, which do provide a full stacktrace and context.

**Comment by tadejm** [comment]
We also struggled getting exceptions reported to Rollbar. They were reported for anything job related but not for request. Something was preventing the exception to bubble up so we ended up setting `handle_exceptions false` for production and fixed it.

**Comment by DangerDawson** [comment]
We ended up fixing this by putting the rack middleware in config.ru e.g.

```
use Honeybadger::Rack::ErrorNotifier
use Honeybadger::Rack::UserFeedback
use Honeybadger::Rack::UserInformer
```

**Comment by ianks** [comment]
I agree that the default behavior is confusing and ends up being a really bad UX, since the defaults make it so your error reporting system doesn’t see 500s in production. All unhandled exceptions should go to error reporting system, yet we should be able to render custom views for these errors. 

I think we’re going to have to monkeypatch this behavior for now 😞

**Comment by jodosha** [comment]
Closing as stale. Feel free to reopen, in case.

**Comment by mcansky** [comment]
so @jodosha , what's the way to handle exceptions towards an exception tracker ?

I guess the "simplest" is to plug into https://github.com/hanami/controller#exceptions-management 

has a standard way to do so in an Hanami app been documented ?
