### ISSUE TITLE
Is `#request` supposed to be memoized for actions?

### ISSUE THREAD

**Issue by tomdalling** [hanami/controller#328]
Looking at [the source for the `#request` method](https://github.com/hanami/controller/blob/5e7ec52331bb31267aa927a7eb7324e196291436/lib/hanami/action/rack.rb#L253) I see that it's memoized. That would indicate that action objects are intended to handle a single request only. Is this intended? I assumed that action objects were intended to be reusable for multiple requests, since `#call` takes a `params` argument.

**Comment by timriley** [comment]
I'll let @jodosha answer in detail, but I can say that this is now seen as undesirable from a design perspective and one of the first things corrected in the Hanami 2 version (see the unstable branch) - actions there are properly "stateless" in that no per-request information is stored.

**Comment by tomdalling** [comment]
Ah, right. I just installed whatever version rubygems gave me, and forgot that the newer work is on a different branch. I see the changes now, and they look good! I'll close this one.
