### ISSUE TITLE
accept syntax in README no longer seems supported

### ISSUE THREAD

**Issue by radar** [hanami/controller#405]
The README suggests:

> You can restrict the accepted MIME types:

```ruby
class Show < Hanami::Action
  accept :html, :json

  def handle(*)
    # ...
  end
end
```

But this syntax no longer appears to be supported in this gem.

**Comment by timriley** [comment]
Thanks @radar, updating this README is one of our last things to do before the release :) 

Looks like @solnic is onto it: https://trello.com/c/R4aGZrA3/345-update-hanami-controller-readme
