### ISSUE TITLE
Add action name to Rack environment

### ISSUE THREAD

**Issue by timriley** [hanami/controller#445]
This will help APM products like AppSignal integrate with Hanami actions without monkey patches.

See [this forum post](https://discourse.hanamirb.org/t/questions-for-improving-the-appsignal-apm-integration-with-hanami-2/989) and the corresponding AppSignal PR (https://github.com/appsignal/appsignal-ruby/pull/1113) for details.

**Comment by tombruijn** [comment]
I've tried to solve this issue in https://github.com/hanami/controller/pull/446 🙂
